### ISSUE TITLE
Consider a Clojure version

### ISSUE THREAD

**Issue by seancorfield** [reagent-project/reagent-cursor#1]
Most of the protocols in the ClojureScript version don't exist in Clojure so the code would look quite different.

It looks like a Clojure version would implement `IRef`, `IReference` and `IAtom` although extending `ARef` and implementing `IAtom` might be easier. Need to give this a bit more thought.

See https://github.com/clojure/clojure/blob/master/src/jvm/clojure/lang/Atom.java

**Comment by Frozenlock** [comment]
I guess this can be closed.

**Comment by seancorfield** [comment]
Yeah, I'm not entirely sure what to do with the library at this point. It almost makes more sense to move it out of the `reagent-project` organization altogether (back to my account?) and develop it independently.
