### ISSUE TITLE
How to inspect cursors when debugging?

### ISSUE THREAD

**Issue by LiFlash** [reagent-project/reagent-cursor#14]
Hi,
I'm starting to use reagent-cursor in my small app and wonder how you would debug the state of the app. When using (println my-cursor) i get the message 'too much recursion' most of the time.
How do you inspect your app-state (which is full of cursors)

Greetings, Joe

**Comment by Frozenlock** [comment]
Do you have a minimum working example for the behavior you are describing?

Personally I just print it in the repl, just like normal atoms.

**Comment by LiFlash** [comment]
Do you use a browser connected repl for this? Currently I only have the js console in firefox, because austin didn't work for some time. Maybe this changed in the meanwhile...
Here is a minimal example to reproduce this:
```
(let [my-atom (atom {:path {:x [1]
                                           :y [2]}})
       my-cursor (cursor [:path] my-atom)]
    (reset! my-atom (update-in @my-atom [:paths] into [my-cursor]))
    (println my-atom))
```

The important thing here is that the app-state contains a cursor(list) to some data in the same atom.

**Comment by Frozenlock** [comment]
Yes, I'm using a browser repl for this. (Tho I suppose you could print the atom/cursor into a div...)

It seems you are somehow inserting the cursor inside itself. When trying to print it, it will look up in the atom for its value, see a cursor, try to print it... look up the atom for its value, see a cursor, try to print it...

Usually, you are not supposed to insert an atom inside itself:

```clj
(let [my-atom (atom {:path {:x [1] :y [2]}})] (reset! my-atom {:a my-atom}))

;; *BOOOOM*
;; #<RangeError: Maximum call stack size exceeded>
```

The only reason it doesn't blow up immediately when using cursors is because they deref the atom only when needed. Printing the cursor forces a deref, which is why everything explodes.

**Comment by LiFlash** [comment]
So you say putting a cursor into the atom is like referencing the atom itself within itself? Ok, that would explain a lot ;) I think my other issue is solved then, too.

What is your best practice for managing the cursors? I have some 'raw' data in a map and want to manage them in a (sorted) list too. For example {:a [1 2], :b [2 3]} and a vector [cursor-to-b, cursor-to-a].
If a cursor is a reference to the whole atom, I would have to store the cursors in second atom, right? How do you do that in your apps? Or do you define the cursors seperately like (def cursor-to-b ...)? That would imply a lot of (def ...)s

Thanks for your fast responses.

Greetings, Joe

**Comment by Frozenlock** [comment]
I'm not sure you are approaching cursors with the right mindset...

I never have to 'manage' cursors; I just create them on the fly when I want a sub-component to not be aware of anything else.

I described a personal use-case here:
https://github.com/reagent-project/reagent-cookbook/issues/11 

In short:
```clj
(defn cell-component [cell-a] ;; <----- expects a CELL atom
  [:g (draw-my-cell @cell-a)])
  
(defn grid-component [grid-a] ;; <---- expects an atom of the entire grid
  [:g (for [coord (get-all-coords grid-a)]
        [cell-component (c/cur grid-a coord)])]) ;; <---- create cursors on the fly.
```

From the point of view of `cell-component`, we gave it an atom containing ONLY the data for the given cell. 

From the app-state management however, everything is still cleanly kept in a single atom named `grid-a`.

**Comment by LiFlash** [comment]
You are right, maybe my mindset is the problem here.
What I want to do, is store some data and 'referencing' it in multiple places in the state. My app-state would look like this:
```
{:data {:elem1 {...}, :elem2 {...}}
 :data-filter [elem1-cursor]
 :generated-data {:property "some value", :refs [cursor-elem2]}}
```
How would you do that? If not using the cursors as references, I only see the possibility to store some keys or paths of the desired referenced elements. Like in your example that means I have to call the (cur ...) function all the time.
So instead of 
``(for [ref (:refs @my-elem-cursor)] 
      (my-fn (cur my-atom ref)))``
I just wanna wright
``(map my-fn (:refs @my-elem-cursor))``

Or
``(filter-fn (:data-filter @my-atom))``
instead of
```
(let [elems (mapv #(cur my-atom %) (:data-filter @my-atom))]
  (filter-fn elems))
```
These examples imply that I'm referencing by path. Using keys would make it even more verbose. Does this make sense to you?
The goal is to store some data and use it in different contexts. But maybe my mindset is still the problem...

**Comment by Frozenlock** [comment]
> What I want to do, is store some data and 'referencing' it in multiple places in the state.

What would you do without cursors? Why do you need a reference to another state? Do you really need to have access to a 'live' state, or could you just copy stuff around?


Could you provide a real (but minimal) example of what you are trying to do?

**Comment by LiFlash** [comment]
First of all, thanks for your support! I'll try to describe in short my pilot project, which I use to get used to clojure(script).
It's a small release planning tool for agile teams. That is, I have some stories, sprints, epics and releases. The stories are the base data which are then grouped by sprints, epics or releases as needed. A small example of the app-state would look like this:
```clojure
{:stories {:key1 {story-map}, :key2 {another-story-map}}
 :sorted-stories [sorted list of stories] ;;<--- story references sorted by priority
 :releases {:release1 {:name "release-name",
                       :end-date "some-date"
                       :stories [stories contained in release1]}} ;;<--- here are some references
 :epics {:epic1 {:name "epic-name"
                 :description "epic description"
                 :stories [stories contained in epic1]}} ;;<--- story references again
 :story-filter [stories to filter]} ;;<--- more references; the filter is updated when (de)selecting releases or epics
```
Without cursors I would have to copy the stories multiple times or use keys or paths as the referencing value (see above). Copying could get expensive in a big backlog and I would have to keep all the places in sync.
The :story-filter is still a little bit ugly, because two cursors to the same element don't seem to be equal and I have to look for the (story) key to find out if a distinct story is contained in the filter. Because of that the filter currently is a list of keys, but it would be nice to have some references here,too.

Hope the example is helpfull. Please let me know what you think about it.

**Comment by seancorfield** [comment]
Github isn't really intended for "support" questions about the projects. This discussion would be much better on the Reagent mailing list - see the Reagent README for the link: https://github.com/reagent-project/reagent

I'm closing this issue.

**Comment by LiFlash** [comment]
You're right. I opened this request https://groups.google.com/forum/#!topic/reagent-project/JYodWYtxFvs
